name: karmour
favicon: null
layout_spectrum: 0.6122893739957362
typography_spectrum: 0.2186832504812628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9953583136666566
  lightness: 0.019697906682267785
  saturation: 0.9603016120381653
  rhythmicContrast: 0.5058276671916246
purpose: []
